// ── CNP shared data ───────────────────────────────────────────────
// Generic sample video (Big Buck Bunny — Creative Commons) for popups.

const A = (p) => `${process.env.PUBLIC_URL}${p}`;

export const CNP_PROJECTS = [
  {
    id: "cnp",
    name: "Cool Nerdy People Collabs",
    client: "Cool Nerdy People Collabs",
    year: "2025",
    img: A("/assets/proyects/CNP.png"),
    logo: A("/assets/proyects/logos/Logo_CNPBlack.png"),
    video: A("/assets/proyects/videos/ReelCNP.mp4"),
    // palette
    bg: "#00BF63",
    fg: "#000000",
    accent: "#d142a4",
    chip: "#000000",
    chipFg: "#00BF63",
    tag: "COOL NERDY PEOPLE",
    services: ["Brand Identity", "3D / Toy Design", "Art Direction"],
    keywords: ["streetwear", "collectible", "gaming", "latino culture"],
    desc: "Una cápsula coleccionable que traduce el barrio a vinilo. Curamos el cruce entre gaming global y cultura local — sin perder el acento.",
  },
  {
    id: "barrios",
    name: "Barrios Latinos",
    client: "Call of Duty: Mobile",
    year: "2025",
    img: A("/assets/proyects/codm.png"),
    logo: A("/assets/proyects/logos/Logo_CD_M.png"),
    video: A("/assets/proyects/videos/barrios.mp4"),
    // palette
    bg: "#FFEA2E",
    fg: "#000000",
    accent: "#d142a4",
    chip: "#000000",
    chipFg: "#FFEA2E",
    tag: "ACTIVISION",
    services: ["Brand Identity", "3D / Toy Design", "Art Direction"],
    keywords: ["streetwear", "collectible", "gaming", "latino culture"],
    desc: "Una cápsula coleccionable que traduce el barrio a vinilo. Curamos el cruce entre gaming global y cultura local — sin perder el acento.",
  },
  {
    id: "sams",
    name: "Sams Club Hot Sale",
    client: "Hot Sale",
    year: "2023",
    img: A("/assets/proyects/hotsale.png"),
    logo: A("/assets/proyects/logos/Logo_Sams.png"),
    video: A("/assets/proyects/videos/barrios.mp4"),
    bg: "#3979FB",
    fg: "#ffffff",
    accent: "#820cea",
    chip: "#191919",
    chipFg: "#00bf63",
    tag: "Sams Club",
    services: ["Game Design", "Character", "Web App"],
    keywords: ["tamagotchi", "virtual pet", "nostalgia", "playful"],
    desc: "Una mascota digital que alimentas con criterio, no con clicks. Low ego, high care. El juguete que cuida de vuelta.",
  },
  {
    id: "depend",
    name: "Depend Podcast",
    client: "Feminine Depend: Podcast de Mujerona a Mujerona",
    year: "2023",
    img: A("/assets/proyects/depend-podcast.png"),
    logo: A("/assets/proyects/logos/Logo_Depend.png"),
    video: A("/assets/proyects/videos/barrios.mp4"),
    bg: "#CB6CE6",
    fg: "#ffffff",
    accent: "#191919",
    chip: "#191919",
    chipFg: "#faff22",
    tag: "Feminine Depend",
    services: ["Hardware", "UX Writing", "Branding"],
    keywords: ["pager", "Y2K", "signal", "comms"],
    desc: "Un buscapersonas reinventado para la era del ruido. 1 new message. La señal por encima del scroll infinito.",
  },
  {
    id: "costa",
    name: "Costa Coffee",
    client: "COSTA Coffee",
    year: "2024",
    img: A("/assets/proyects/costa.png"),
    logo: A("/assets/proyects/logos/Logo_CostaC.png"),
    video: A("/assets/proyects/videos/CostaCoffee.mp4"),
    bg: "#F38CE5",
    fg: "#ffffff",
    accent: "#191919",
    chip: "#191919",
    chipFg: "#ffffff",
    tag: "COSTA Coffee",
    services: ["Packaging", "Sound Identity", "Editorial"],
    keywords: ["cassette", "analog", "nostalgia", "limited"],
    desc: "Edición limitada en cinta transparente. Recuperamos el ritual del play físico para una generación que solo conoció el stream.",
  },

  {
    id: "axe",
    name: "CNP Axe",
    client: "AXESS BY AXE",
    year: "2023",
    img: A("/assets/proyects/axe.png"),
    logo: A("/assets/proyects/logos/Logo_AxessbyAxe.png"),
    video: A("/assets/proyects/videos/AXESS.mp4"),
    bg: "#F95C4B",
    fg: "#ffffff",
    accent: "#820cea",
    chip: "#191919",
    chipFg: "#1E1E1E",
    tag: "AXE",
    services: ["Game Design", "Character", "Web App"],
    keywords: ["tamagotchi", "virtual pet", "nostalgia", "playful"],
    desc: "Una mascota digital que alimentas con criterio, no con clicks. Low ego, high care. El juguete que cuida de vuelta.",
  },
];

// Merch collage — fashion editorial (text always present per card)
export const CNP_MERCH = [
  {
    id: "cap",
    img: A("/assets/merch-1.png"),
    name: "Nerdy Cap + Bandana",
    price: "$38",
    drop: "OJAI SERIES",
    color: "#2892fb",
  },
  {
    id: "tee",
    name: "Low Ego Tee",
    price: "$45",
    drop: "THE CODE",
    color: "#e2ff0d",
    typeOnly: true,
    sub: "Heavyweight cotton. One statement.",
  },
  {
    id: "tote",
    name: "Curaduría Tote",
    price: "$28",
    drop: "THE FILTER",
    color: "#d142a4",
    typeOnly: true,
    sub: "Carry less. Choose better.",
  },
  {
    id: "stk",
    name: "Cursor Sticker Pack",
    price: "$12",
    drop: "LA SEÑAL",
    color: "#5944ff",
    typeOnly: true,
    sub: "Not decoration. A signal.",
  },
  {
    id: "hoodie",
    name: "Signal Hoodie",
    price: "$72",
    drop: "THE DROP",
    color: "#f95c4b",
    typeOnly: true,
    sub: "Tech as tool. Worn warm.",
  },
];

export const CNP_SOCIAL = [
  {
    id: "linkedin",
    label: "CNP on LinkedIn",
    href: "https://www.linkedin.com/",
  },
    {
    id: "spacer",
    label: "",
    href: "",
  },
  {
    id: "instagram",
    label: "CNP on Instagram",
    href: "https://www.instagram.com/",
  },

];
